import React from "react";

type Props = {
  generatedCode: string;
};

const WebsiteDesign = ({ generatedCode }: Props) => {
  return (
    <div className="flex-1 p-5 h-[91vh] overflow-auto">
      {generatedCode && generatedCode.length > 0 ? (
        <div
          className=""
          dangerouslySetInnerHTML={{
            __html: `
          <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <meta name="description" content="Generated by AI Website Generator" />
              <title>AI Website Generator</title>

              <!-- Tailwind CSS CDN -->
              <script src="https://cdn.tailwindcss.com"></script>

              <!-- Flowbite CSS CDN -->
              <link
                href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
                rel="stylesheet"
              />
              <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

              <!-- Font Awesome CDN -->
              <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5t/1uO4eqvEF7N6Z4+Yf3f+gKp3rGkU2N0X8sV2d9aVqgPNO8+zJ6F8e5w5pX5Z5c5m5b5m5b5m5b5m5b5mA==" crossorigin="anonymous" referrerpolicy="no-referrer" crossorigin="anonymous" referrerpolicy="no-referrer"
              />

              <!-- Chart.js CDN for charts & graphs -->
              <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

              <!-- AOS CDN for animations -->
              <link
                href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
                rel="stylesheet"
              />
              <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>

              <!-- Gsap CDN for advanced animations -->
              <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>

              <!-- Lottie CDN for Lottie animations -->
              <script src="https://cdnjs.cloudflare.com/ajax/libs/lottie-web/5.10.2/lottie.min.js"></script>

              <!-- Swiper CDN for sliders -->
              <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.4.5/swiper-bundle.min.css"
              />
              <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.4.5/swiper-bundle.min.js"></script>

              <!-- Optional: Tooltip & Popover library (Tippy.js) -->
              <link
                rel="stylesheet"
                href="https://unpkg.com/tippy.js@6/dist/tippy.css"
              />
              <script src="https://unpkg.com/@popperjs/core@2"></script>
              <script src="https://unpkg.com/tippy.js@6/dist/tippy.umd.min.js"></script>
            </head> 
              ${generatedCode} 
            </html>
        `,
          }}
        ></div>
      ) : (
        <div className="flex items-center justify-center h-full">
          <div className="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
            <div className="flex items-center justify-center w-12 h-12 mb-4 mx-auto bg-blue-100 rounded-lg dark:bg-blue-900">
              <svg
                className="w-6 h-6 text-blue-600 dark:text-blue-300"
                fill="currentColor"
                viewBox="0 0 20 20"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  fillRule="evenodd"
                  d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z"
                  clipRule="evenodd"
                ></path>
              </svg>
            </div>
            <h5 className="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white text-center">
              Website Preview
            </h5>
            <p className="mb-3 font-normal text-gray-700 dark:text-gray-400 text-center">
              Your website template will appear here.
              <br /> Please wait AI is generating your code.
            </p>
            <div className="flex justify-center">
              <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default WebsiteDesign;
