import React from "react";

type Props = {
  generatedCode: string;
};

const WebsiteDesign = ({ generatedCode }: Props) => {
  return (
    <div className="flex-1 p-5 h-[91vh] overflow-auto">
      <div
        className=""
        dangerouslySetInnerHTML={{
          __html: `
          <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <meta name="description" content="Generated by AI Website Generator" />
              <title>AI Website Generator</title>

              <!-- Tailwind CSS CDN -->
              <script src="https://cdn.tailwindcss.com"></script>

              <!-- Flowbite CSS CDN -->
              <link
                href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
                rel="stylesheet"
              />
              <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

              <!-- Font Awesome CDN -->
              <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5t/1uO4eqvEF7N6Z4+Yf3f+gKp3rGkU2N0X8sV2d9aVqgPNO8+zJ6F8e5w5pX5Z5c5m5b5m5b5m5b5m5b5mA==" crossorigin="anonymous" referrerpolicy="no-referrer" crossorigin="anonymous" referrerpolicy="no-referrer"
              />

              <!-- Chart.js CDN for charts & graphs -->
              <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

              <!-- AOS CDN for animations -->
              <link
                href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
                rel="stylesheet"
              />
              <script src="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.js"></script>

              <!-- Gsap CDN for advanced animations -->
              <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.2/gsap.min.js"></script>

              <!-- Lottie CDN for Lottie animations -->
              <script src="https://cdnjs.cloudflare.com/ajax/libs/lottie-web/5.10.2/lottie.min.js"></script>

              <!-- Swiper CDN for sliders -->
              <link
                rel="stylesheet"
                href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.4.5/swiper-bundle.min.css"
              />
              <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/8.4.5/swiper-bundle.min.js"></script>

              <!-- Optional: Tooltip & Popover library (Tippy.js) -->
              <link
                rel="stylesheet"
                href="https://unpkg.com/tippy.js@6/dist/tippy.css"
              />
              <script src="https://unpkg.com/@popperjs/core@2"></script>
              <script src="https://unpkg.com/tippy.js@6/dist/tippy.umd.min.js"></script>
            </head> 
              ${generatedCode} 
            </html>
        `,
        }}
      ></div>
    </div>
  );
};

export default WebsiteDesign;
